config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users
  root 'main#index'
  get 'main/game' => 'main#game', :as => 'game'
  get 'main/result' => 'main#result', :as => 'result'
  get 'main/getcoordinate' => 'main#getcoordinate', :as => 'getcoordinate'
  get 'main/rank' => 'main#rank', :as => 'rank'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :number, :uniqueness => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale = :rus
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def game
    @image = rand(1..10)
    cookies[:someval] = @image
  end

  # Вывод результата игры и подсчет баллов
  def result
   @name = Image.find_by_number(cookies[:someval])[:name]
   @lat = Image.find_by_number(cookies[:someval])[:lat].to_f
   @lng = Image.find_by_number(cookies[:someval])[:lng].to_f
   @latcor = flash[:latcor].to_f
   @lngcor = flash[:lngcor].to_f
   @distance = distance(@lat, @lng, @latcor, @lngcor)
   @score = score(@distance)
   cookies[:score] = @score
   list
  end

  # Получение отмеченных пользователем координат
  def getcoordinate
    flash[:latcor] = params[:lat]
    flash[:lngcor] = params[:lng]
  end

  #Вывод рейтинга
  def rank
    @users = User.all.order(score: :desc)
  end

private

  # Расчет расстояния между координатами
  def distance(lat1,lng1,lat2,lng2) #
   dlat = deg2rad(lat2 - lat1)
   dlng = deg2rad(lng1 - lng2)
   d = Math.sin(dlat/2)**2 + Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2))* Math.sin(dlng)**2
   ((2 * Math.atan2(Math.sqrt(d), Math.sqrt(1-d))) * 6371).round(3)
  end

  # Подсчет баллов
  def score(distance)
    (1000 - 0.1 * distance).to_i
  end

  def deg2rad(deg)
    deg * (3.14/180)
  end

  # Добавление баллов в бд
  def list
    if current_user.score.nil?
      User.find_by_email(current_user.email).update(score: cookies[:score])
    else
      d = User.find_by_email(current_user.email)[:score]
      User.find_by_email(current_user.email).update(score: (cookies[:score].to_i + d))
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('layouts.application.title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
    <span><%=t('layouts.application.hello') %><%= current_user.email %></span>
    <%= link_to t('layouts.application.exit'), destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to t('layouts.application.enter'), new_user_session_path %> или <%= link_to t('layouts.application.registration'), new_user_registration_path %>
  <% end %>
  <ul class="language">
    <li><%= link_to "Русский", {locale: :rus} %></li>
    <li><%= link_to 'English', {locale: :en}  %></li>
  </ul>
  <%= yield %>
  </body>
</html>

app/views/main/game.html.erb
<body style="background: #FFF;">
<h2><%= t('main.game.quiz') %></h2>
<%= image_tag ('/assets/' + @image.to_s + '.png'), class: 'image'%>
<div id="map"></div>
<%= form_tag(result_path, :method => "get") do %>
  <%= submit_tag(t('main.game.guess-button'), class: 'guess-button') %>
<%end %>
<script type="text/javascript">
  var marker;
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: {lat: 25.363882, lng: 131.044922 }
        });
        map.addListener('click', function(e) {
            placeMarkerAndPanTo(e.latLng, map);
        });
    }
    function placeMarkerAndPanTo(latLng, map) {
        marker = new google.maps.Marker({
            position: latLng,
            map: map
        });
        map.panTo(latLng);
        var latcor = marker.getPosition().lat();
        var lngcor = marker.getPosition().lng();
        jQuery.ajax({
            data: {'lat':  latcor, 'lng': lngcor},
            dataType: 'script',
            type: 'get',
            url: "/main/getcoordinate",
        });
    }
</script>
</body>
<script async defer src="https://maps.googleapis.com/maps/api/js?libraries=places&key=[YOUR KEY]&callback=initMap"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

app/views/main/index.html.erb
<div class="input-form">
  <%= form_tag(game_path, :method => "get", class: "start-game") do %>
    <%= submit_tag(t('main.index.start-button'), class: "start-button")%>
  <% end %>
  <%= form_tag(rank_path, :method => "get") do %>
    <%= submit_tag(t('main.index.rank-button'), class: "rank-button") %>
  <% end %>
</div>

app/views/main/rank.html.erb
<body style="background: white;">
<h2><%=t('main.rank.title') %></h2>

<table>
  <thead>
  <tr>
    <th><%= t('main.rank.email') %></th>
    <th><%= t('main.rank.score') %></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.score %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('main.rank.back'), root_path %>
</body>

app/views/main/result.html.erb
<body style="background: #FFF;">
<div id="map"></div>
<h2><%= @name%></h2>
<h2><%=t('main.result.miss-first') + @distance.to_s + t('main.result.miss-second')%></h2>
<h2><%= t('main.result.earn-first')+ @score.to_s + t('main.result.earn-second')%></h2>
<%= form_tag(root_path, :method => "get") do %>
  <%= submit_tag(t('main.result.play-again'), class: 'play-again') %>
<%end %>
</body>
<script type="text/javascript">
  function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 3,
            center: {lat: 0, lng: 100},
            mapTypeId: 'terrain'
      });
      var lat = <%= @lat.to_f %>;
      var lng = <%= @lng.to_f %>;
      var latcor = <%= @latcor.to_f %>;
      var lngcor = <%= @lngcor.to_f %>;
      var flightPlanCoordinates = [
            {lat: lat, lng: lng },
            {lat: latcor, lng: lngcor}
            ];
      var flightPath = new google.maps.Polyline({
            path: flightPlanCoordinates,
            geodesic: true,
            strokeColor: '#FF0000',
            strokeOpacity: 1.0,
            strokeWeight: 2
      });
      var marker = new google.maps.Marker({position: {lat: lat, lng: lng}, map: map});
      var marker = new google.maps.Marker({position: {lat: latcor, lng: lngcor}, map: map});
      flightPath.setMap(map);
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?libraries=places&key=[YOUR KEY[&callback=initMap"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>